service: telegram-bot

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    BOT_TOKEN: ${env:BOT_TOKEN}
    WEBAPP_URL: ${env:WEBAPP_URL}

functions:
  webhook:
    handler: handler.webhook
    events:
      - httpApi:
          path: /webhook
          method: POST
